"use client";
import { Handle, Position, type NodeProps } from "@xyflow/react";
import { useState } from "react";
import { createPortal } from "react-dom";
import { Badge } from "@/components/ui/Badge";
import { ImageAnnotationEditor } from "./ImageAnnotationEditor";
import { useCanvasStore } from "@/store/canvasStore";
import type { CanvasNode, ImageAnnotation } from "@/types/canvas";

const icons: Record<string, string> = { prompt: "✦", text: "T", image: "◈", video: "▶", audio: "♫", storyboard: "▦", reference: "⌁", output: "↗" };
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
const text = (value: unknown) => typeof value === "string" ? value : "";

function NodePreview({ node, onView, onAnnotate }: { node: CanvasNode; onView(url: string): void; onAnnotate(url: string): void }) {
  const value = node.data.output?.value, details = record(value), raw = record(details.raw), rawContent = record(raw.content); const imageUrl = text(details.imageUrl) || (typeof value === "string" ? value : ""); const audioUrl = text(details.audioUrl), videoUrl = text(details.videoUrl) || text(details.resultUrl) || text(details.finalVideoUrl) || text(rawContent.video_url), generatedText = text(details.generatedText);
  if (node.data.nodeType === "image" && imageUrl) return <div className="mt-2"><button onClick={() => onView(imageUrl)} className="block w-full overflow-hidden rounded-md border border-slate-700 hover:border-cyan-300"><img src={imageUrl} alt="Generated result" className="h-36 w-full object-cover"/></button><div className="mt-2 flex gap-2"><button onClick={() => onView(imageUrl)} className="text-[10px] text-cyan-300 hover:text-cyan-100">View full image</button><button onClick={() => onAnnotate(imageUrl)} className="text-[10px] text-violet-200 hover:text-violet-100">Annotate & Refine</button></div></div>;
  if (node.data.nodeType === "audio" && audioUrl) return <audio className="mt-2 w-full" controls src={audioUrl}/>;
  if (node.data.nodeType === "video" && videoUrl) return <video className="mt-2 h-32 w-full rounded-md object-cover" controls src={videoUrl}/>;
  if (node.data.nodeType === "storyboard" && Array.isArray(value)) return <div className="mt-2 max-h-48 space-y-2 overflow-y-auto pr-1">{value.map((scene) => { const item = record(scene); return <div key={String(item.sceneNumber)} className="rounded-md border border-slate-700 bg-slate-950/50 p-2"><p className="text-[10px] font-semibold text-cyan-200">SCENE {String(item.sceneNumber)}</p><p className="mt-1 text-[11px] leading-4 text-slate-200">{text(item.description)}</p><p className="mt-1 text-[10px] text-slate-500">{text(item.camera)} · {String(item.duration)}s</p></div>; })}</div>;
  if (node.data.nodeType === "output" && text(details.format)) return <div className="mt-2"><p className="text-[11px] font-semibold text-cyan-200">{text(details.format)}</p><p className="mt-1 text-[10px] text-slate-500">{Array.isArray(details.assets) ? `${details.assets.length} connected asset(s)` : "No connected assets"}</p></div>;
  return <p className="mt-2 line-clamp-3 text-[11px] leading-4 text-slate-400">{generatedText || node.data.output?.summary || node.data.prompt || node.data.instruction || node.data.storyBrief || node.data.notes || "Configure this node in the inspector."}</p>;
}

export function AnnotatedCustomNode({ id, data, selected }: NodeProps<CanvasNode>) {
  const removeNode = useCanvasStore((state) => state.removeNode), duplicateNode = useCanvasStore((state) => state.duplicateNode), createImageRevision = useCanvasStore((state) => state.createImageRevision);
  const [viewUrl, setViewUrl] = useState(""); const [annotatingUrl, setAnnotatingUrl] = useState(""); const node = { id, data } as CanvasNode; const isWaiting = record(data.output?.value).status === "pending";
  return <><div className={`w-[280px] rounded-xl border bg-[#101c29] shadow-xl shadow-black/20 ${selected ? "border-cyan-400" : "border-slate-700"}`}><Handle type="target" position={Position.Left} className="!h-2.5 !w-2.5 !border-2 !border-[#101c29] !bg-cyan-400"/><div className="flex items-center gap-2 border-b border-slate-800 px-3 py-2"><span className="grid h-6 w-6 place-items-center rounded-md bg-cyan-400/10 text-sm text-cyan-300">{icons[data.nodeType]}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-100">{data.title}</p><p className="text-[10px] uppercase tracking-widest text-slate-500">{data.nodeType}</p></div><Badge status={data.status}/></div><div className="min-h-20 px-3 py-2"><NodePreview node={node} onView={setViewUrl} onAnnotate={setAnnotatingUrl}/>{isWaiting && <p className="mt-2 text-[10px] text-sky-200">Waiting for generation…</p>}{data.error && <p className="mt-2 text-[11px] text-rose-300">{data.error}</p>}{data.revisionOf && <p className="mt-2 text-[10px] text-violet-200">Revision of source image</p>}</div><div className="nodrag flex justify-end gap-1 border-t border-slate-800 px-2 py-1.5"><button onClick={() => duplicateNode(id)} className="rounded px-1.5 py-1 text-[10px] text-slate-400 hover:bg-slate-800 hover:text-cyan-200">Duplicate</button><button onClick={() => removeNode(id)} className="rounded px-1.5 py-1 text-[10px] text-slate-400 hover:bg-slate-800 hover:text-rose-200">Delete</button></div><Handle type="source" position={Position.Right} className="!h-2.5 !w-2.5 !border-2 !border-[#101c29] !bg-cyan-400"/></div>{viewUrl && typeof document !== "undefined" && createPortal(<div className="fixed inset-0 z-[9999] grid place-items-center bg-black/85 p-8" onClick={() => setViewUrl("")}><div className="max-h-full max-w-5xl" onClick={(event) => event.stopPropagation()}><img src={viewUrl} alt="Full generated result" className="max-h-[80vh] max-w-full rounded-lg object-contain"/><button onClick={() => setViewUrl("")} className="mx-auto mt-3 block rounded bg-slate-800 px-4 py-2 text-sm text-white">Close</button></div></div>, document.body)}{annotatingUrl && <ImageAnnotationEditor imageUrl={annotatingUrl} initialAnnotations={data.annotations as ImageAnnotation[] | undefined} initialInstruction={data.revisionInstruction} onClose={() => setAnnotatingUrl("")} onGenerate={(annotations, instruction) => { void createImageRevision(id, annotations, instruction); setAnnotatingUrl(""); }}/>}</>;
}
