export class AIProviderError extends Error { constructor(message: string, public readonly code = "AI_PROVIDER_ERROR", public readonly status = 500) { super(message); this.name = "AIProviderError"; } }
export class AIProviderConfigError extends AIProviderError { constructor(message = "302.AI API key is missing. Please set AI_302_API_KEY in your server environment.") { super(message, "AI_PROVIDER_CONFIG_ERROR", 500); this.name = "AIProviderConfigError"; } }
export class AIProviderHTTPError extends AIProviderError { constructor(message: string, status: number, public readonly body?: unknown) { super(message, "AI_PROVIDER_HTTP_ERROR", status); this.name = "AIProviderHTTPError"; } }
export class TokenStarError extends AIProviderError { constructor(message: string, status = 500) { super(message, "TOKENSTAR_ERROR", status); this.name = "TokenStarError"; } }
const safeProviderDetail = (message: string) => message.replace(/Bearer\s+\S+/gi, "Bearer [redacted]").replace(/\b(sk|vk|ts)-[A-Za-z0-9._-]+/gi, "[redacted]").replace(/((?:api[_-]?key|token|secret|authorization)\s*[:=]\s*["']?)[^\s,"'}]+/gi, "$1[redacted]").replace(/^302\.AI request to /i, "").replace(/^302\.AI request failed \(\d+\):\s*/i, "").slice(0, 4000);
export function normalizeAIError(error: unknown) {
  if (error instanceof TokenStarError) { const detail = safeProviderDetail(error.message); if (error.status === 401) return { message: `TokenStar rejected the request (401). ${detail || "Check TOKENSTAR_API_KEY."}`, code: error.code, status: error.status }; if (error.status === 403) return { message: `TokenStar denied the request (403). ${detail || "The key may be valid, but account permissions, balance, or access to the selected model may be unavailable."}`, code: error.code, status: error.status }; if (error.status === 429) return { message: `TokenStar rate limit reached. ${detail || "Please try again later."}`, code: error.code, status: error.status }; if (error.status === 402) return { message: `TokenStar requires available credits or balance. ${detail || "Please check the account quota."}`, code: error.code, status: error.status }; if (error.status >= 500) return { message: `TokenStar service returned ${error.status}. ${detail || "Please retry later."}`, code: error.code, status: error.status }; return { message: detail, code: error.code, status: error.status }; }
  if (error instanceof AIProviderConfigError) return { message: error.message, code: error.code, status: error.status };
  if (error instanceof AIProviderHTTPError) { if (error.status === 401) return { message: "302.AI authentication failed. Please check AI_302_API_KEY.", code: error.code, status: error.status }; if (error.status === 403) return { message: `302.AI denied this endpoint or model. The API key may be valid, but the selected model, voice, or account permission is unavailable. ${safeProviderDetail(error.message)}`, code: error.code, status: error.status }; if (error.status === 402 || error.status === 429) return { message: "302.AI request was limited. Please check your balance, quota, or rate limit.", code: error.code, status: error.status }; if (error.status >= 500) { const detail = safeProviderDetail(error.message); return { message: detail && detail !== "Unknown response" ? `302.AI service returned ${error.status}: ${detail}` : `302.AI service returned ${error.status}. Please retry later or use the configured default model.`, code: error.code, status: error.status }; } return { message: safeProviderDetail(error.message), code: error.code, status: error.status }; }
  if (error instanceof AIProviderError) return { message: error.message, code: error.code, status: error.status };
  return { message: "AI request failed. Please try again.", code: "AI_PROVIDER_ERROR", status: 500 };
}
