import "server-only";
import type { AIProvider } from "./types";

const pause = (ms = 450) => new Promise((resolve) => setTimeout(resolve, ms));
const safe = (text: string) => text.replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" })[char] ?? char);

export const mockAIProvider: AIProvider = {
  name: "mock",
  async generateText(input) { await pause(); return { text: `Creative draft: ${input.prompt.slice(0, 170)}. The tone is vivid, focused, and ready to develop.` }; },
  async generateImage(input) { await pause(550); const size = input.size || "1024×1024"; const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="520"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#164e63"/><stop offset="1" stop-color="#7c2d12"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="640" cy="130" r="110" fill="#fbbf24" opacity=".8"/><path d="M0 420 Q190 220 370 390 T800 310 V520 H0Z" fill="#0b1320" opacity=".75"/><text x="42" y="55" fill="white" font-family="sans-serif" font-size="22">MOCK IMAGE • ${safe(size)}</text><text x="42" y="475" fill="#dbeafe" font-family="sans-serif" font-size="18">${safe(input.prompt.slice(0, 65))}</text></svg>`; return { imageUrl: `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`, status: "completed" }; },
  async editImageWithAnnotations(input) { await pause(700); const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="520"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#1d4ed8"/><stop offset="1" stop-color="#7c3aed"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><path d="M0 410 Q190 190 390 380 T800 280 V520 H0Z" fill="#0b1320" opacity=".7"/><text x="42" y="58" fill="white" font-family="sans-serif" font-size="23">MOCK REFINED IMAGE</text><text x="42" y="92" fill="#bae6fd" font-family="sans-serif" font-size="16">Annotation instructions applied cleanly</text><text x="42" y="470" fill="#dbeafe" font-family="sans-serif" font-size="17">${safe(input.prompt.slice(0, 70))}</text></svg>`; return { revisedImageUrl: `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`, status: "completed", raw: { sourceImageUrl: input.sourceImageUrl } }; },
  async generateImageRevision(input) { const edited = await this.editImageWithAnnotations({ sourceImageUrl: input.sourceImageUrl, prompt: input.prompt || input.instruction || "Refined visual direction" }); return { imageUrl: edited.revisedImageUrl, status: edited.status, raw: edited.raw }; },
  async generateVideo(input) { await pause(650); return { taskId: "mock-video-task", status: "pending", raw: { prompt: input.prompt, duration: input.duration } }; },
  async generateAudio(input) { await pause(520); return { audioUrl: "", status: "completed", raw: { message: `Audio sketch ready · ${input.text.slice(0, 42)}` } }; },
  async generateStoryboard(input) { await pause(620); return { scenes: Array.from({ length: input.numberOfScenes }, (_, i) => ({ sceneNumber: i + 1, shotNumber: i + 1, description: `${input.storyBrief.slice(0, 72)} - professional beat ${i + 1}`, visualPrompt: `Cinematic keyframe, scene ${i + 1}, ${input.storyBrief.slice(0, 52)}`, imagePrompt: `Film still storyboard frame, consistent characters and setting, ${input.storyBrief.slice(0, 80)}, shot ${i + 1}`, cinematicLanguage: "Classical continuity coverage", blocking: "Clear foreground-midground-background staging", visualContinuity: "Maintain geography, props, and screen direction", characterContinuity: "Same character design, wardrobe, and proportions", sceneContinuity: "Same location palette and production design", composition: ["wide establishing composition", "medium tracking composition", "low-angle dramatic composition", "slow push-in portrait composition"][i % 4], lens: ["24mm", "35mm", "50mm", "85mm"][i % 4], camera: ["Wide orbit", "Close tracking", "Low angle", "Slow push-in"][i % 4], cameraMovement: ["locked-off", "slow dolly", "handheld drift", "controlled push-in"][i % 4], lighting: "Motivated cinematic lighting", colorPalette: "controlled teal, warm highlights, natural skin tones", mood: "Focused and cinematic", actionRhythm: "Readable action beat with a clear start and finish", soundCue: "Subtle ambience and movement accents", transition: "Cut", duration: 3 + (i % 3), negativePrompt: "text overlay, labels, UI, watermark, distorted hands, inconsistent character" })) }; },
  async listModels() { return []; },
  async pollTask(type, taskId) { await pause(300); return type === "video" ? { taskId, videoUrl: "", status: "completed", raw: { message: "Mock video concept complete" } } : { taskId, status: "completed" }; },
};
