import "server-only";
import { request302 } from "./302aiClient";
import { AIProviderError } from "./errors";
type RecordValue = Record<string, unknown>;
const record = (value: unknown): RecordValue => value && typeof value === "object" ? value as RecordValue : {};
const text = (value: unknown) => typeof value === "string" ? value : undefined;
const status = (value: unknown) => ["failed", "error", "cancelled"].includes(String(value).toLowerCase()) ? "failed" : "pending";
export async function createSora2ImageVideo(input: { prompt: string; image: string; duration?: number; resolution?: string }) { const duration = input.duration ?? 4, resolution = input.resolution || "720p"; if (![4, 8, 12].includes(duration)) throw new AIProviderError("Sora-2 image-to-video duration must be 4, 8, or 12 seconds.", "INVALID_SORA_DURATION", 400); if (!["720p", "1080p"].includes(resolution)) throw new AIProviderError("Sora-2 image-to-video resolution must be 720p or 1080p.", "INVALID_SORA_RESOLUTION", 400); const raw = await request302<RecordValue>("/ws/api/v3/openai/sora-2/image-to-video", { method: "POST", body: JSON.stringify({ prompt: input.prompt, image: input.image, duration, resolution }) }); const data = record(raw.data); return { taskId: text(data.id), pollUrl: text(record(data.urls).get), status: "pending" as const, raw }; }
export async function pollSora2ImageVideo(pollUrl: string, fallbackTaskId: string) { let path: string; try { const url = new URL(pollUrl); if (!/api\.302(?:\.ai|ai\.cn|ai\.com)$/i.test(url.hostname)) throw new Error("Unexpected result host"); path = `${url.pathname}${url.search}`; } catch { throw new AIProviderError("Sora-2 task result URL is invalid.", "INVALID_SORA_POLL_URL", 400); } const raw = await request302<RecordValue>(path); const data = record(raw.data); const outputs = Array.isArray(data.outputs) ? data.outputs : []; const videoUrl = text(outputs[0]); return { taskId: text(data.id) || fallbackTaskId, videoUrl, status: videoUrl ? "completed" as const : status(data.status), raw }; }
