import "server-only";
import { tokenstarGet, tokenstarJsonRequest } from "./tokenstarClient";
import type { NormalizedVideoTask, TokenStarContentItem, TokenStarCreateVideoInput, TokenStarCreateVideoResponse, TokenStarPollVideoResponse } from "./tokenstarTypes";
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
const text = (value: unknown) => typeof value === "string" ? value : undefined;
const taskId = (raw: Record<string, unknown>) => text(raw.id) || text(raw.task_id) || text(raw.taskId);
const normalized = (task: string | undefined, raw: unknown): NormalizedVideoTask => { const root = record(raw), data = record(root.data), output = record(root.output); const resultUrl = text(root.result_url) || text(root.resultUrl) || text(data.result_url) || text(data.resultUrl) || text(output.result_url) || text(output.resultUrl); const status = String(root.status || data.status || output.status || "").toLowerCase(); return { taskId: task || taskId(root), resultUrl, status: resultUrl || ["completed", "success", "succeeded", "done"].includes(status) ? "completed" : ["failed", "error", "cancelled"].includes(status) ? "failed" : "pending", raw }; };
const bool = (value: string | undefined, fallback: boolean) => value === undefined ? fallback : value.toLowerCase() === "true";
const contentFor = (input: TokenStarCreateVideoInput, assetMode: boolean): TokenStarContentItem[] => { const content: TokenStarContentItem[] = [{ type: "text", text: input.prompt }]; if (assetMode && input.referenceImageAssetUrl) content.push({ type: "image_url", image_url: { url: input.referenceImageAssetUrl }, role: "reference_image" }); if (assetMode && input.referenceVideoAssetUrl) content.push({ type: "video_url", video_url: { url: input.referenceVideoAssetUrl }, role: "reference_video" }); if (assetMode && input.referenceAudioAssetUrl) content.push({ type: "audio_url", audio_url: { url: input.referenceAudioAssetUrl }, role: "reference_audio" }); return content; };
export async function createSeedanceVideo(input: TokenStarCreateVideoInput): Promise<NormalizedVideoTask> { const raw = await tokenstarJsonRequest<TokenStarCreateVideoResponse>("/v1/video/generations", { model: input.model || process.env.TOKENSTAR_VIDEO_MODEL || "seedance-2.0-fast", content: contentFor(input, false), generate_audio: input.generateAudio ?? bool(process.env.TOKENSTAR_GENERATE_AUDIO, true), ratio: input.ratio || process.env.TOKENSTAR_DEFAULT_RATIO || "16:9", duration: input.duration || Number(process.env.TOKENSTAR_DEFAULT_DURATION || 8), ...(input.callbackUrl ? { callback_url: input.callbackUrl } : {}) }); return { taskId: taskId(raw), status: "pending", raw }; }
export async function createSeedanceAssetVideo(input: TokenStarCreateVideoInput): Promise<NormalizedVideoTask> { const raw = await tokenstarJsonRequest<TokenStarCreateVideoResponse>("/v1/video/generations", { model: input.model || process.env.TOKENSTAR_VIDEO_ASSET_MODEL || "seedance-2.0-asset-fast", content: contentFor(input, true), generate_audio: input.generateAudio ?? bool(process.env.TOKENSTAR_GENERATE_AUDIO, true), ratio: input.ratio || process.env.TOKENSTAR_DEFAULT_RATIO || "16:9", duration: input.duration || 5, resolution: input.resolution || process.env.TOKENSTAR_DEFAULT_RESOLUTION || "720p", ...(input.callbackUrl ? { callback_url: input.callbackUrl } : {}) }); return { taskId: taskId(raw), status: "pending", raw }; }
export async function pollSeedanceVideo(id: string): Promise<NormalizedVideoTask> { const raw = await tokenstarGet<TokenStarPollVideoResponse>(`/v1/video/generations/${encodeURIComponent(id)}`); return normalized(id, raw); }
