import "server-only";
import { tokenstarFormRequest, tokenstarJsonRequest } from "./tokenstarClient";
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
const idFrom = (raw: unknown) => { const root = record(raw), data = record(root.data); return typeof root.id === "string" ? root.id : typeof root.GroupId === "string" ? root.GroupId : typeof root.AssetId === "string" ? root.AssetId : typeof data.id === "string" ? data.id : typeof data.GroupId === "string" ? data.GroupId : typeof data.AssetId === "string" ? data.AssetId : undefined; };
export async function createAssetGroup(name: string) { const raw = await tokenstarJsonRequest("/volc/asset/CreateAssetGroup", { model: "volc-asset", Name: name }); return { groupId: idFrom(raw), raw }; }
export async function listAssetGroups(filterName?: string) { const raw = await tokenstarJsonRequest("/volc/asset/ListAssetGroups", { model: "volc-asset", ...(filterName ? { Filter: { Name: filterName } } : {}), PageNumber: 1, PageSize: 10 }); return { raw }; }
export async function createAssetFromUrl(input: { groupId: string; name: string; assetType: "Image" | "Video" | "Audio"; url: string }) { const raw = await tokenstarJsonRequest("/volc/asset/CreateAsset", { model: "volc-asset", GroupId: input.groupId, Name: input.name, AssetType: input.assetType, URL: input.url }); const assetId = idFrom(raw); return { assetId, assetUrl: assetId ? `asset://${assetId}` : undefined, raw }; }
export async function createAssetFromFile(input: { groupId: string; name: string; assetType: "Image" | "Video" | "Audio"; file: Blob }) { const form = new FormData(); form.append("model", input.assetType === "Video" ? "volc-asset-video" : input.assetType === "Audio" ? "volc-asset-audio" : "volc-asset"); form.append("file", input.file, "asset"); form.append("GroupId", input.groupId); form.append("Name", input.name); form.append("AssetType", input.assetType); const raw = await tokenstarFormRequest("/volc/asset/CreateAsset", form); const assetId = idFrom(raw); return { assetId, assetUrl: assetId ? `asset://${assetId}` : undefined, raw }; }
export async function listAssets(input: { groupId?: string; name?: string }) { const raw = await tokenstarJsonRequest("/volc/asset/ListAssets", { model: "volc-asset", Filter: { ...(input.name ? { Name: input.name } : {}), ...(input.groupId ? { GroupIds: [input.groupId], GroupType: "AIGC" } : {}) }, PageNumber: 1, PageSize: 10 }); return { raw }; }
